### ISSUE TITLE
Asking about the license

### ISSUE THREAD

**Issue by Mohammad-Aliraqi** [mkbreuer/ToolPlus#2]
Hi mkbreuer,

Sorry to contact you by creating an issue (do not know how to do so otherwise)

I am just kind of confused about the license of this/these plugin(s), if I am creating some assets for commercial use, am I allowed to use this/these plugins to help me boosting my productivity?

Regards

**Comment by mkbreuer** [comment]
Hy Mohammad-Aliraqi, you can use all of this plugins for your non-commercial and commercial work.
Please respect the GNU General Public License inside the scripts.
The GPL is a copyleft license, which means that derivative work can only be distributed under the same license terms. Follow the link below if you want more information about this license:
https://en.wikipedia.org/wiki/GNU_General_Public_License
Cheers!

**Comment by Mohammad-Aliraqi** [comment]
Thank you for the prompt reply!

I understood this part from the very beginning. What confused me is the sentence in "README.md" which says:
> T+ Addons on this GitHub are collections of my own scripts, free uncommercial scripts and addons from allover.

This confused me about what does this means and I thought it might mean that the created assets (models) using these addons should not be for commercial (even though I know that the license for the code itself is GPL).

Anyway, I think it might be my bad over-engineering here 😄.

Thanks and best regards

**Comment by mkbreuer** [comment]
Yes your a right! I rewritten it for better understanding.
